# Generated by Django 6.0.3 on 2026-04-09 14:47

import django.contrib.postgres.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('COMPANY', 'Company'), ('SCHOOL', 'School'), ('UNIVERSITY', 'University'), ('GOVERNMENT', 'Government'), ('CHILDREN', 'Children Facility'), ('HOMELESS', 'Homeless Shelter'), ('ORGANIZATION', 'organization')], default='COMPANY', max_length=20, verbose_name='Customer Type')),
                ('name', models.CharField(max_length=127, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('street', models.CharField(max_length=253, verbose_name='Street Name')),
                ('post_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Postal Code')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DE', verbose_name='Phone Number')),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=63), blank=True, help_text="Example: ['Cleaning', 'Security', 'Web App']", null=True, verbose_name='Services')),
            ],
        ),
    ]
